# Run rake with target like this.
#   > rake target=iq-r

# plc section
plc:
  # MITSUBISHI iQ-R
  iq-r:                     # It's a target name
    cpu: iq-r               # It's just a comment.
    protocol: mc_protocol   # It's a protocol to communicate with PLC.
    host: 192.168.0.10      # It's PLC's IP address or dns name.
    # port: 5007              # It's PLC's port no. If it's not descript here, use default port.

  # You can describe targets multiply.

  # Keyence KV-5000
  kv5000:
    cpu: kv-5000
    protocol: kv_protocol
    host: 192.168.0.11
    # port: 8501

  # Raspberry Pi
  raspberrypi:
    cpu: Raspberry Pi
    io: # assign gpio to x and y
      inputs:
      - x0: 4
      - x1: 17
      - x2: 27
      outputs:
      - y0: 18
      - y1: 23
      - y2: 24

# default section
default:
  # If you set target iq-r, `rake` is same as `rake target=iq-r`.
  # default target is emulator.
  # target: iq-r
